/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.vista;

import com.iudigital.controller.FuncionarioController;
import com.iudigital.domain.Funcionario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Main extends javax.swing.JFrame {
    
    private final FuncionarioController funcionarioController;
    private static final String[] COLUMNS = {"ID", "Tipo de Identificación", "Número de Identificación", "Nombres", "Apellidos", "Estado Civil", "Sexo", "Dirección", "Teléfono"};
    private static final String SELECCIONE = "-- SELECCIONE --";
   
    public Main() {
        initComponents();
        txtIdEdit.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();
    }
    
    private void listFuncionarios(){
        cbxFuncionarios.removeAllItems();
        Funcionario fun = new Funcionario();
        fun.setNombres(SELECCIONE);
        fun.setApellidos("");
        cbxFuncionarios.addItem(fun);
        tblFuncionarios.removeAll();
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for(String COLUMN : COLUMNS){
            defaultTableModel.addColumn(COLUMN);
        }
        tblFuncionarios.setModel(defaultTableModel);
        
        List<Funcionario> funcionarios = funcionarioController.getFuncionarios();
        if(funcionarios.isEmpty()){
            return;
        }
        defaultTableModel.setRowCount(funcionarios.size());
        int row = 0;
        for(Funcionario funcionario: funcionarios){
            defaultTableModel.setValueAt(funcionario.getIdFuncionario(), row, 0);
            defaultTableModel.setValueAt(funcionario.getTipoIdentificacion(), row, 1);
            defaultTableModel.setValueAt(funcionario.getNumeroIdentificacion(), row, 2);
            defaultTableModel.setValueAt(funcionario.getNombres(), row, 3);
            defaultTableModel.setValueAt(funcionario.getApellidos(), row, 4);
            defaultTableModel.setValueAt(funcionario.getEstadoCivil(), row, 5);
            defaultTableModel.setValueAt(funcionario.getSexo(), row, 6);
            defaultTableModel.setValueAt(funcionario.getDireccion(), row, 7);
            defaultTableModel.setValueAt(funcionario.getTelefono(), row, 8);
            row++;
            cbxFuncionarios.addItem(funcionario);
        }
    }
    
    private void addListener(){
        cbxFuncionarios.addItemListener(event -> {
            Funcionario selectedFun = (Funcionario) event.getItem();
            if(selectedFun.getNombres().equals(SELECCIONE)){
                txtIdEdit.setText("");
                txtTipoIdentificacionEdit.setText("");
                txtNumeroIdentificacionEdit.setText("");
                txtNombresEdit.setText("");
                txtApellidosEdit.setText("");
                txtEstadoCivilEdit.setText("");
                txtSexoEdit.setText("");
                txtDireccionEdit.setText("");
                txtTelefonoEdit.setText("");
            }else{
                txtIdEdit.setText(String.valueOf(selectedFun.getIdFuncionario()));
                txtTipoIdentificacionEdit.setText(selectedFun.getTipoIdentificacion());
                txtNumeroIdentificacionEdit.setText(selectedFun.getNumeroIdentificacion());
                txtNombresEdit.setText(selectedFun.getNombres());
                txtApellidosEdit.setText(selectedFun.getApellidos());
                txtEstadoCivilEdit.setText(selectedFun.getEstadoCivil());
                txtSexoEdit.setText(selectedFun.getSexo());
                txtDireccionEdit.setText(selectedFun.getDireccion());
                txtTelefonoEdit.setText(selectedFun.getTelefono());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTPanel = new javax.swing.JTabbedPane();
        jPCrear = new javax.swing.JPanel();
        jPFuncionario = new javax.swing.JPanel();
        lblTipoIdentificacion = new javax.swing.JLabel();
        lblNumeroIdentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtTipoIdentificacion = new javax.swing.JTextField();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPEditar = new javax.swing.JPanel();
        jPEdit = new javax.swing.JPanel();
        lblFuncionariosEdit = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        lblIdEdit = new javax.swing.JLabel();
        txtIdEdit = new javax.swing.JTextField();
        lblTipoIdentificacionEdit = new javax.swing.JLabel();
        txtTipoIdentificacionEdit = new javax.swing.JTextField();
        lblNumeroIdentificacionEdit = new javax.swing.JLabel();
        txtNumeroIdentificacionEdit = new javax.swing.JTextField();
        lblNombresEdit = new javax.swing.JLabel();
        txtNombresEdit = new javax.swing.JTextField();
        lblApellidosEdit = new javax.swing.JLabel();
        txtApellidosEdit = new javax.swing.JTextField();
        lblEstadoCivlEdit = new javax.swing.JLabel();
        txtEstadoCivilEdit = new javax.swing.JTextField();
        lblSexoEdit = new javax.swing.JLabel();
        txtSexoEdit = new javax.swing.JTextField();
        lblDireccionEdit = new javax.swing.JLabel();
        txtDireccionEdit = new javax.swing.JTextField();
        lblTelefonoEdit = new javax.swing.JLabel();
        txtTelefonoEdit = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlHighlight);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setText("Gestion de Funcionarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jTPanel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N

        jPFuncionario.setBackground(new java.awt.Color(203, 242, 242));
        jPFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite los siguientes campos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblTipoIdentificacion.setText("Tipo de Identificación");

        lblNumeroIdentificacion.setText("Numero Identificacón");

        lblNombres.setText("Nombres");

        lblApellidos.setText("Apellidos");

        txtTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoIdentificacionActionPerformed(evt);
            }
        });

        lblEstadoCivil.setText("Estado Civil");

        lblSexo.setText("Sexo");

        lblDireccion.setText("Dirección");

        lblTelefono.setText("Teléfono");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPFuncionarioLayout = new javax.swing.GroupLayout(jPFuncionario);
        jPFuncionario.setLayout(jPFuncionarioLayout);
        jPFuncionarioLayout.setHorizontalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombres)
                    .addComponent(lblApellidos)
                    .addComponent(lblNumeroIdentificacion)
                    .addComponent(lblTipoIdentificacion))
                .addGap(18, 18, 18)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPFuncionarioLayout.createSequentialGroup()
                        .addGap(6, 453, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPFuncionarioLayout.createSequentialGroup()
                        .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombres)
                                .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDireccion)
                            .addComponent(lblEstadoCivil)
                            .addComponent(lblSexo)
                            .addComponent(lblTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSexo)
                            .addComponent(txtEstadoCivil)
                            .addComponent(txtTelefono)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jPFuncionarioLayout.setVerticalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(lblEstadoCivil)
                    .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoIdentificacion)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroIdentificacion)
                        .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPCrearLayout = new javax.swing.GroupLayout(jPCrear);
        jPCrear.setLayout(jPCrearLayout);
        jPCrearLayout.setHorizontalGroup(
            jPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCrearLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34))
        );
        jPCrearLayout.setVerticalGroup(
            jPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCrearLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTPanel.addTab("Crear Funcionario", jPCrear);

        jPEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite el campo que desea modificar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblFuncionariosEdit.setText("Funcionarios");

        lblIdEdit.setText("ID");

        lblTipoIdentificacionEdit.setText("Tipo de Identificación");

        lblNumeroIdentificacionEdit.setText("Numero de Identificación");

        lblNombresEdit.setText("Nombres");

        lblApellidosEdit.setText("Apellidos");

        lblEstadoCivlEdit.setText("Estado Civil");

        lblSexoEdit.setText("Sexo");

        lblDireccionEdit.setText("Dirección");

        lblTelefonoEdit.setText("Teléfono");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEditLayout = new javax.swing.GroupLayout(jPEdit);
        jPEdit.setLayout(jPEditLayout);
        jPEditLayout.setHorizontalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoIdentificacionEdit)
                    .addComponent(lblFuncionariosEdit)
                    .addComponent(lblNumeroIdentificacionEdit)
                    .addComponent(lblNombresEdit)
                    .addComponent(lblApellidosEdit))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoIdentificacionEdit)
                    .addComponent(txtNumeroIdentificacionEdit)
                    .addComponent(txtNombresEdit)
                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdEdit)
                    .addComponent(lblEstadoCivlEdit)
                    .addComponent(lblSexoEdit)
                    .addComponent(lblDireccionEdit)
                    .addComponent(lblTelefonoEdit))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addComponent(txtEstadoCivilEdit)
                    .addComponent(txtSexoEdit)
                    .addComponent(txtDireccionEdit)
                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPEditLayout.setVerticalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionariosEdit)
                    .addComponent(lblIdEdit)
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoIdentificacionEdit)
                    .addComponent(txtTipoIdentificacionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivlEdit)
                    .addComponent(txtEstadoCivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroIdentificacionEdit)
                    .addComponent(txtNumeroIdentificacionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoEdit)
                    .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombresEdit)
                    .addComponent(txtNombresEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionEdit)
                    .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidosEdit)
                    .addComponent(lblTelefonoEdit)
                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jTPanel.addTab("Editar Funcionario", jPEditar);

        getContentPane().add(jTPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 890, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoIdentificacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(txtTipoIdentificacion.getText().trim().length() == 0 || txtNumeroIdentificacion.getText().trim().length() == 0 ||
                txtNombres.getText().trim().length() == 0 || txtApellidos.getText().trim().length() == 0 || txtEstadoCivil.getText().trim().length() == 0 ||
                txtSexo.getText().trim().length() == 0 || txtDireccion.getText().trim().length() == 0 || txtTelefono.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            return;
        }
        
        Funcionario funcionario = new Funcionario();
        funcionario.setTipoIdentificacion(txtTipoIdentificacion.getText().trim());
        funcionario.setNumeroIdentificacion(txtNumeroIdentificacion.getText().trim());
        funcionario.setNombres(txtNombres.getText().trim());
        funcionario.setApellidos(txtApellidos.getText().trim());
        funcionario.setEstadoCivil(txtEstadoCivil.getText().trim());
        funcionario.setSexo(txtSexo.getText().trim());
        funcionario.setDireccion(txtDireccion.getText().trim());
        funcionario.setTelefono(txtTelefono.getText().trim());
        
        funcionarioController.create(funcionario);
        txtTipoIdentificacion.setText("");
        txtNumeroIdentificacion.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEstadoCivil.setText("");
        txtSexo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        listFuncionarios();
        JOptionPane.showMessageDialog(null, "Funcionario creado con exito");
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        if(txtIdEdit.getText().trim().length() == 0 || txtTipoIdentificacionEdit.getText().trim().length() == 0 || txtNumeroIdentificacionEdit.getText().trim().length() == 0 ||
                txtNombresEdit.getText().trim().length() == 0 || txtApellidosEdit.getText().trim().length() == 0 || txtEstadoCivilEdit.getText().trim().length() == 0 ||
                txtSexoEdit.getText().trim().length() == 0 || txtDireccionEdit.getText().trim().length() == 0 || txtTelefonoEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            return;
        }
        
        Funcionario funcionario = new Funcionario();
        funcionario.setIdFuncionario(Integer.valueOf(txtIdEdit.getText().trim()));
        funcionario.setTipoIdentificacion(txtTipoIdentificacionEdit.getText().trim());
        funcionario.setNumeroIdentificacion(txtNumeroIdentificacionEdit.getText().trim());
        funcionario.setNombres(txtNombresEdit.getText().trim());
        funcionario.setApellidos(txtApellidosEdit.getText().trim());
        funcionario.setEstadoCivil(txtEstadoCivilEdit.getText().trim());
        funcionario.setSexo(txtSexoEdit.getText().trim());
        funcionario.setDireccion(txtDireccionEdit.getText().trim());
        funcionario.setTelefono(txtTelefonoEdit.getText().trim());
        
        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el Funcionario", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(opt == 0){
            funcionarioController.updateFuncionario(funcionario);
            txtIdEdit.setText("");
            txtNumeroIdentificacionEdit.setText("");
            txtNombresEdit.setText("");
            txtApellidosEdit.setText("");
            txtEstadoCivilEdit.setText("");
            txtSexoEdit.setText("");
            txtDireccionEdit.setText("");
            txtTelefonoEdit.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario creado con exito");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        if (txtIdEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un Funcionario de la Lista");
            txtIdEdit.requestFocus();
            return;
        }
        Funcionario funcionario = new Funcionario(Integer.valueOf(txtIdEdit.getText().trim()));
        
        int opt = JOptionPane.showConfirmDialog(null, "Está seguro de borrar Funcionario", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opt == 0){
            funcionarioController.deleteFuncionario(funcionario);
            txtIdEdit.setText("");
            txtNumeroIdentificacionEdit.setText("");
            txtNombresEdit.setText("");
            txtApellidosEdit.setText("");
            txtEstadoCivilEdit.setText("");
            txtSexoEdit.setText("");
            txtDireccionEdit.setText("");
            txtTelefonoEdit.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario eliminado con exito");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Funcionario> cbxFuncionarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCrear;
    private javax.swing.JPanel jPEdit;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPanel;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidosEdit;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionEdit;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblEstadoCivlEdit;
    private javax.swing.JLabel lblFuncionariosEdit;
    private javax.swing.JLabel lblIdEdit;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombresEdit;
    private javax.swing.JLabel lblNumeroIdentificacion;
    private javax.swing.JLabel lblNumeroIdentificacionEdit;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexoEdit;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoEdit;
    private javax.swing.JLabel lblTipoIdentificacion;
    private javax.swing.JLabel lblTipoIdentificacionEdit;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosEdit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEdit;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtEstadoCivilEdit;
    private javax.swing.JTextField txtIdEdit;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombresEdit;
    private javax.swing.JTextField txtNumeroIdentificacion;
    private javax.swing.JTextField txtNumeroIdentificacionEdit;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexoEdit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEdit;
    private javax.swing.JTextField txtTipoIdentificacion;
    private javax.swing.JTextField txtTipoIdentificacionEdit;
    // End of variables declaration//GEN-END:variables
}
